### DISCUSSION TITLE
Window Icon

### DISCUSSION THREAD

**Discussion by xmha97** [filips123/PWAsForFirefox#168] [Q&A] [answered]
How I can remove window icon? like Android apps (WSA)
![image](https://user-images.githubusercontent.com/23485114/173380139-72e797eb-4852-4633-bb5d-3c587ed47ca0.png)

**Comment by filips123** [comment, marked as answer]
You can add this to `userChrome.css`:

```css
@-moz-document url('chrome://browser/content/browser.xhtml') {
  .tab-icon-image {
    display: none !important;
  }
}
```
