### ISSUE TITLE
How I can use userChrome.css

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#151]
How I can use `userChrome.css`?
I want to remove the Firefox Application Button.
![image](https://user-images.githubusercontent.com/23485114/167290697-691569ca-d83b-4516-9f01-5b9d92f33f73.png)

**Comment by filips123** [comment]
1. Inside your PWA profile, open `about:config` (with F6) and set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`.
2. Open your PWA profile directory, go to `chrome` subdirectory and create file `userChrome.css` (so, `%APPDATA%\FirefoxPWA\profiles\00000000000000000000000000\chrome\userChrome.css` on default profile on Windows).
3. Add this to `userChrome.css`:
   ```css
   @-moz-document url('chrome://browser/content/browser.xhtml') {
       #PanelUI-menu-button {
           display: none !important;
       }
   }
   ```
5. Restart your PWAs.
