### ISSUE TITLE
Icon bar cannot be hidden

### ISSUE THREAD

**Issue by mirenradia** [filips123/PWAsForFirefox#190]
### Description

Since the v2.0.x update, I can no longer hide the icon bar. I have tried in an old profile created with an older version (probably v1.4.x) and also with a new web app created in a new profile.

### Steps to Reproduce

1. Create a new PWA.
2. Open it and navigate to `about:config` (e.g. by pressing F6).
3. Toggle `firefoxpwa.enableHidingIconBar` to `true` (it defaults to `false`).
4. Close and re-open PWA.
5. Attempt to hide the icon bar via one of the following methods
  a. Press Ctrl+Alt.
  b. Right click on the icon bar and uncheck 'Icon Bar'.
  c. Right click on any toolbar and go to 'Customize Toolbar'. In the bottom left, click the 'Toolbars' dropdown and uncheck 'Icon Bar'.
6. The icon bar is still visible.

### Environment

* Operating system: Ubuntu 22.04
* System architecture: x86_64 (amd64)
* Desktop environment:  KDE Plasma 5.24.4, KWin 5.24.4
* Installation method:  DEB
* PWAsForFirefox extension version: 2.0.1
* PWAsForFirefox native version: 2.0.1
* Firefox version: 103.0 (PWA runtime), 103.0.1 (normal firefox)

**Comment by filips123** [comment]
I can reproduce it on Kubuntu, so maybe it's Linux or KDE-specific bug. Will try to check why this happens.

**Comment by filips123** [comment]
I quick workaround is to comment out/remove the following rules from `/usr/share/firefoxpwa/userchrome/profile/chrome/pwa/content/browser.css`, then enable "Always patch runtime and profile" in the extension settings (you can later disable it again) and restart your web apps:

```css
  @media (-moz-gtk-csd-available) {
    #titlebar {
      visibility: hidden;
    }

    #titlebar > * {
      visibility: visible;
    }

    :root[tabsintitlebar][sizemode="normal"]:not([gtktiledwindow="true"]) body {
      border-top-left-radius: env(-moz-gtk-csd-titlebar-radius);
      border-top-right-radius: env(-moz-gtk-csd-titlebar-radius);
    }
  }
```

I will try to release a fix soon.
