### ISSUE TITLE
Spacing and Alignment

### ISSUE THREAD

**Issue by maymage** [filips123/PWAsForFirefox#359]
Hi all, 

as you can see here on Firefox-Youtube-PWA with 

Hamburger Menu
  --> More tools
    -- > Customize toolbar
      --> Density

set to `Touch`  

![grafik](https://github.com/filips123/PWAsForFirefox/assets/36572014/395d6672-b3e8-44db-b95f-016a8c6427e3)

the following issues occur on the headerbar

* Youtube icon and  `YouTube `text to the left are not centered
* the `Hamurger Menu` is not aligned close to the `Close Button`, which is disturbing in comparison to other apps on my system 

---

This is on

* Fedora 38
* GNOME 44.2
* FirefoxPWA 2.6.1
* Firefox 114.0.2

**Comment by filips123** [comment]
I don't know why the icon and title aren't vertically centered for you. I tested it on Fedora GNOME and it appears fine, even when using the touch density. Does it also happen if you create a fresh profile?

![screenshot](https://github.com/filips123/PWAsForFirefox/assets/16626308/9b2a8e10-3201-4911-bfe0-531d33962cd5)

By default, the icon and title are left aligned on all platforms (other than macOS), because there are quite a lot of different desktop environments and configuration options, and it's hard to detect which style should be used, so there is just a single default (Windows-like) style. However, you can add custom CSS yourself to customize how the icon bar should look.

For example, for a more GNOME-like experience, you can add this CSS to your `userChrome.css`:

```css
@-moz-document url('chrome://browser/content/browser.xhtml') {
  /* Horizontally center the title element */
  .site-info {
    justify-content: center !important;
  }

  /* Remove the icon element */
  .tab-icon-image {
    display: none !important;
  }

  /* Remove space between hamburger menu and window controls */
  .titlebar-spacer[type="post-tabs"] {
    width: 0 !important;
  }
}
```

With those changes, this is how the titlebar should look:

![screenshot](https://github.com/filips123/PWAsForFirefox/assets/16626308/2802e27e-b177-4b2b-b814-8c3993066765)

You also need to enable `toolkit.legacyUserProfileCustomizations.stylesheets` inside `about:config` for this to work. However, centering the title horizontally currently doesn't work because of a bug. I'll fix it in the next version.
