### ISSUE TITLE
Top accent color is missing on Windows 10

### ISSUE THREAD

**Issue by zeek-zag** [filips123/PWAsForFirefox#535]
### Steps to Reproduce

1. Install any PWA,
2. Open the PWA window,
3. Notice the top accent color missing.

### Additional Information

My best guess it's problem with the CSS stylesheet. [Firefox UI Fix](https://github.com/black7375/Firefox-UI-Fix) also had the same problem and it got fixed a few versions ago. I tried to replicate their fix but I don't know CSS enough to make it work.

**How the window looks after opening:**
![How it is](https://github.com/user-attachments/assets/4e9e5a34-451f-4967-a1a1-6a3607c346d9)

**How it should look:**
![How it should be](https://github.com/user-attachments/assets/2ba7ad9a-c892-43b1-a6ec-addd0e050775)

### Affected Windows

Every single PWA window is affected.

### Environment

* Operating system: Windows 10 Pro 22H2 19045.4651
* System architecture: x64
* Installation method: MSI
* PWAsForFirefox extension version: 2.12.1
* PWAsForFirefox native version: latest bundled with the extension
* PWAsForFirefox runtime version: latest bundled with the extension
* Firefox version: 129

**Comment by filips123** [comment]
It works fine for me on Windows 11, so it's probably specific to Windows 10. Do you know when/how exactly the problem was fixed in Firefox-UI-Fix so I can take a look at it?

**Comment by zeek-zag** [comment]
Thanks for the quick response. I think it's related to this bit:
```css
@media (-moz-bool-pref: "userChrome.compatibility.os") and (-moz-platform: windows) and (-moz-windows-accent-color-in-titlebar) {
  :root[sizemode="normal"][tabsintitlebar] #navigator-toolbox {
    border-top-color: AccentColor !important;
  }
}
```
Top accent vanishes from main Firefox window when I remove it. It's in the OS compatibility section in [leptonChrome.css](https://github.com/black7375/Firefox-UI-Fix/blob/master/css/leptonChrome.css#L13842)

**Comment by filips123** [comment]
You can try adding this to your `userChrome.css`:

```css
@media (-moz-platform: windows) and (-moz-windows-accent-color-in-titlebar) {
  :root[sizemode="normal"][tabsintitlebar] #navigator-toolbox {
    border-top-color: AccentColor !important;
  }
}
```

This is the same as the original version, but without one check for pref. You can find instructions for enabling `userChrome.css` [here](https://pwasforfirefox.filips.si/help/faq/#how-to-apply-custom-css-to-web-apps).

If it works, I will try to include this by default in the future versions.

**Comment by zeek-zag** [comment]
Accent color was staying on the title bar even with windows unfocused so I dug a bit more in the lepton css and added another bit to your snippet:

```css
@media (-moz-platform: windows) {
    :root[sizemode="normal"][tabsintitlebar] #navigator-toolbox {
      border-top: 0.5px solid rgb(47, 47, 47) !important;
    }
    :root[sizemode="normal"][tabsintitlebar]:-moz-window-inactive #navigator-toolbox {
      border-top-color: rgb(57, 57, 57) !important;
    }
  }

@media (-moz-platform: windows) and (-moz-windows-accent-color-in-titlebar) {
    :root[sizemode="normal"][tabsintitlebar] #navigator-toolbox {
      border-top-color: AccentColor !important;
    }
  }
```
It works great now. Thank you for your guidance on this!

**Focused:**
![Screenshot from 2024-08-12 11-17-45](https://github.com/user-attachments/assets/5425d6a3-095c-451b-a13a-9624344e8ff1)
**Unfocused:**
![Screenshot from 2024-08-12 11-17-50](https://github.com/user-attachments/assets/e280406c-a8de-4b0a-bea5-9fe085e3314f)
