### ISSUE TITLE
How to remove application menu button?

### ISSUE THREAD

**Issue by LethalHatred** [filips123/PWAsForFirefox#603]
### Problem Description

I understand that this menu is important but it is so eye catching and ugly. Is there any way to remove it or maybe hide? I'm just a bit of a perfectionist and I would be very happy to hide it.

**Comment by filips123** [comment]
Which menu exactly do you mean?

**Comment by LethalHatred** [comment]
![0059](https://github.com/user-attachments/assets/167e61a4-49ac-469b-9073-4a0860e6b3a8)

I meam this menu. Thanks for your response

**Comment by filips123** [comment]
You can use the following custom CSS:

```css
@-moz-document url('chrome://browser/content/browser.xhtml') {
  #PanelUI-menu-button {
    visibility: collapse !important;
  }
}
```

You can check instructions for applying custom CSS [here](https://pwasforfirefox.filips.si/help/faq/#how-to-apply-custom-css-to-web-apps).
